

//List of exercise that needs to be excluded

List<String> get_blacklist() {
  List<String> blacklist = [
    'Abcd',
    'Bigmarms'
    'Test',
    'Awesome',
    'Bdeadlift',
    'What',
    'Aalex Gambe Alte al Muro',
    'Bicep',
    'Biceps',
    'Chin Ups',
    'Crunch',
    'Deadlifts',
    'ExerA',
    'Upper Body',
    'Treee',
    'TestBicep',
    'Test Pullups',
    'Squat',
    'Snach',
    'Shay',
    'Razboj',
    'Arch Hold',
    'Arms',
    'Arnold Shoulder Press',
    'BenchPress',
    'Bike Ride',
    'Billexercise',
    'Body Squats'
    'Boxing',
    'Brent',
    'Cherry Pickers',
    'Diagonal Shoulder Press',
    'Dumbbell Split Squat',
    'Dumbbell Squat',
    'Fentes Avant',
    'Free Weight Lats Pulldown',
    'Glute',
    'Hammer Curls',
    'Jazz Cersixe',
    'Lift',
    'Lifts',
    'Low Row Machine',
    'Metka',
    'Moroti',
    'my Exercise',
    'Nuevo',
    'Nuevo Ejercicio',
    'Paralalle',
    'Perfect Push Up',
    'Peso Muerto',
    'Pompes',
    'Propadanje',
    'Pullover With Dumbbell',
    'Push Press',
    'Romanian Deadlift',
    'Sads',
    'Snatch',
    'Super Squat',
    'Swim',
    'Trazioni Alla Sbarra Presa Inversa',
    'Triceps Bench Press One Barbell',
    'Triceps Machine',
    'Wyciskanie Skos',

  ];

  return blacklist;
}
